# 在Spring Boot中多环境配置文件名需要满足application-{profile}.properties/yml的格式，
# 其中{profile}对应你的环境标识，
spring:
  profiles:
    active:
      - test

mybatis:
  #  以注解类型扫描类
  type-aliases-package: entity:com.lihang.springboot.entity
